### ISSUE TITLE
Could NOT find GTest (FairRoot)

### ISSUE THREAD

**Issue by aphecetche** [AliceO2Group/AliceO2#307] opened 2017-04-05 10:01 UTC
Hi,

Started an AliceO2 build (using alibuild) from scratch a few minutes ago and got a new thing I did not get e.g. yesterday. Something new in FairRoot ?

[log.txt](https://github.com/AliceO2Group/AliceO2/files/895851/log.txt)

CMake Error at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindGTest.cmake:194 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  fairmq/test/CMakeLists.txt:9 (find_package)

**Comment by sawenzel** [comment] 2017-04-05 10:03
This is due to a change in FairRoot. The problem is more in the build system and was already fixed with the master branch of alidist.

**Closed** 2017-04-05 10:11 UTC

**Comment by ktf** [comment] 2017-04-05 13:19
There are actually a bunch of issues in the current FairRoot dev, when trying to use it with AliceO2.. I am looking into them.
