### ISSUE TITLE
git clang-format does not correct for lines longer than 120 characters

### ISSUE THREAD

**Issue by a-mathis** [AliceO2Group/AliceO2#1121] opened 2018-05-25 08:18 UTC
... but TRAVIS CI complains

**Comment by sawenzel** [comment] 2018-05-25 08:46
There was a change in policy introduced by #1089.
Clang-format is no longer supposed to check the line width. This should now be done manually.
See discussion in #1089 for more infos.

This is hence not a bug/issue. Closing.

**Closed by sawenzel** 2018-05-25 08:46 UTC
