### ISSUE TITLE
Coding Guidelines violations

### ISSUE THREAD

**Issue by ihrivnac** [AliceO2Group/AliceO2#707] opened 2017-12-06 11:14 UTC
While making changes for MT simulation I noticed that several coding guidelines are not followed.
1) use of tabulations is not allowed, see the rule "Spaces vs. Tabs" in "ALICE O² C++ Naming & Formatting Rules"; I attach below the list of files where the TABs are detected. It would be nice to get this automatically checked when reviewing a pull request.
2) static local variables are not allowed, see "Static Variables in functions" in "ALICE O² C++ Coding Guidelines"; they are present in detector codes in ProcessHit() functions (TOF, TPC, TRD)
3) protected data members are not allowed, see "Access Control" in "ALICE O² C++ Coding Guidelines"; this guideline seems to be not followed everywhere
===
Here is the list of files with tabulations:
TAB detected in ./CCDB/src/ConditionMetaData.cxx
TAB detected in ./CCDB/src/GridStorage.cxx
TAB detected in ./CCDB/src/IdPath.cxx
TAB detected in ./CCDB/src/IdRunRange.cxx
TAB detected in ./CCDB/src/LocalStorage.cxx
TAB detected in ./CCDB/src/Manager.cxx
TAB detected in ./Common/Field/src/MagFieldFact.cxx
TAB detected in ./Common/Field/src/MagneticField.cxx
TAB detected in ./Common/Field/test/testMagneticField.cxx
TAB detected in ./DataFormats/Headers/src/DataHeader.cxx
TAB detected in ./DataFormats/Headers/test/testDataHeader.cxx
TAB detected in ./DataFormats/simulation/src/MCCompLabel.cxx
TAB detected in ./DataFormats/simulation/test/testMCCompLabel.cxx
TAB detected in ./Detectors/Base/src/GeometryManager.cxx
TAB detected in ./Detectors/Base/test/testDetID.cxx
TAB detected in ./Detectors/EMCAL/simulation/src/SpaceFrame.cxx
TAB detected in ./Detectors/FIT/simulation/src/Detector.cxx
TAB detected in ./Detectors/ITSMFT/common/base/src/SegmentationAlpide.cxx
TAB detected in ./Detectors/ITSMFT/common/reconstruction/src/Cluster.cxx
TAB detected in ./Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx
TAB detected in ./Detectors/ITSMFT/common/simulation/src/AlpideSimResponse.cxx
TAB detected in ./Detectors/ITSMFT/common/simulation/src/Chip.cxx
TAB detected in ./Detectors/ITSMFT/common/simulation/src/Digitizer.cxx
TAB detected in ./Detectors/ITSMFT/common/simulation/src/Hit.cxx
TAB detected in ./Detectors/ITSMFT/common/simulation/src/SimulationAlpide.cxx
TAB detected in ./Detectors/ITSMFT/common/simulation/test/testAlpideSimResponse.cxx
TAB detected in ./Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
TAB detected in ./Detectors/ITSMFT/ITS/reconstruction/src/CookedTrackerTask.cxx
TAB detected in ./Detectors/ITSMFT/ITS/reconstruction/src/TrivialClusterer.cxx
TAB detected in ./Detectors/ITSMFT/ITS/simulation/src/Detector.cxx
TAB detected in ./Detectors/ITSMFT/ITS/simulation/src/DigitizerTask.cxx
TAB detected in ./Detectors/ITSMFT/ITS/simulation/src/V11Geometry.cxx
TAB detected in ./Detectors/ITSMFT/MFT/base/src/Flex.cxx
TAB detected in ./Detectors/ITSMFT/MFT/base/src/GeometryTGeo.cxx
TAB detected in ./Detectors/ITSMFT/MFT/base/src/HalfDisk.cxx
TAB detected in ./Detectors/ITSMFT/MFT/base/src/HalfDiskSegmentation.cxx
TAB detected in ./Detectors/ITSMFT/MFT/base/src/HalfSegmentation.cxx
TAB detected in ./Detectors/ITSMFT/MFT/base/src/HeatExchanger.cxx
TAB detected in ./Detectors/ITSMFT/MFT/base/src/Ladder.cxx
TAB detected in ./Detectors/ITSMFT/MFT/base/src/LadderSegmentation.cxx
TAB detected in ./Detectors/ITSMFT/MFT/base/src/Support.cxx
TAB detected in ./Detectors/ITSMFT/MFT/reconstruction/src/devices/FileSink.cxx
TAB detected in ./Detectors/ITSMFT/MFT/reconstruction/src/devices/Merger.cxx
TAB detected in ./Detectors/ITSMFT/MFT/reconstruction/src/devices/Sampler.cxx
TAB detected in ./Detectors/ITSMFT/MFT/simulation/src/Detector.cxx
TAB detected in ./Detectors/TOF/base/src/Geo.cxx
TAB detected in ./Detectors/TOF/simulation/src/Detector.cxx
TAB detected in ./Detectors/TPC/reconstruction/src/BoxClusterer.cxx
TAB detected in ./Detectors/TPC/reconstruction/src/Cluster.cxx
TAB detected in ./Detectors/TPC/reconstruction/src/GBTFrameContainer.cxx
TAB detected in ./Detectors/TPC/reconstruction/src/TPCCATracking.cxx
TAB detected in ./Detectors/TPC/simulation/src/DigitContainer.cxx
TAB detected in ./Detectors/TPC/simulation/src/DigitCRU.cxx
TAB detected in ./Detectors/TPC/simulation/src/DigitPad.cxx
TAB detected in ./Detectors/TPC/simulation/src/DigitRow.cxx
TAB detected in ./Detectors/TPC/simulation/src/DigitTime.cxx
TAB detected in ./Detectors/TPC/simulation/src/GEMAmplification.cxx
TAB detected in ./Framework/DebugGUI/src/imgui.cxx
TAB detected in ./Generators/src/Pythia6Generator.cxx
TAB detected in ./Generators/src/Pythia8Generator.cxx
TAB detected in ./Steer/src/O2RunAna.cxx
TAB detected in ./Utilities/aliceHLTwrapper/src/Component.cxx
TAB detected in ./Utilities/aliceHLTwrapper/src/runComponent.cxx
TAB detected in ./Utilities/aliceHLTwrapper/src/SystemInterface.cxx
TAB detected in ./Utilities/DataCompression/test/test_dc_primitives.cxx
TAB detected in ./Utilities/Publishers/src/DataPublisherDevice.cxx

**Comment by ktf** [comment] 2017-12-13 22:40
I fixed all the tabs in  #732. The other two points, while valid, are frankly not actionable. If you have specific examples which you think should be fixed, possibly with an associated PR, we can for sure take a look, otherwise I am closing this.

**Closed by ktf** 2017-12-13 22:40 UTC

**Comment by ihrivnac** [comment] 2017-12-15 14:30
I believe that as the coding guidelines were agreed by the O2 project, they should be also followed in the code. 
For 2. I indicated the code where the violations are present.
For 3. these is just a list of classes in one specific category:
Detectors/Base/include/BaseCluster.h
Detectors/Base/include/DetMatrixCache.h
Detectors/Base/include/Detector.h
Detectors/Base/include/GeometryManager.h
Detectors/Base/include/Track.h
Detectors/Base/include/TrackReference.h

I believ it's up to the developers to provide a fix (and PR); the reason why I open this issue was rather to bring attention to the fact that there are some guidelines which are either ignored by developers or considered not important (?)  So it would be good to make a point on this, and in case the developers find them eg. too restrictive, they should be changed.

Otherwise it makes not good sense to me to have a guidelines document which is however not followed in the code.

Maybe I did not post this in a right forum ...

**Comment by mkrzewic** [comment] 2017-12-15 14:42
Hi, the fact that some guidelines are consistently not followed might mean (at least) one of 2 things:
- stubborn developers, here some rule enforcement might help.
- a rule might need revising - possibly from time to time this might be needed as we learn, as the industry evolves and as new coding concepts become available (e.g. c++17, c++20). I noticed the current guidelines, while quite well put together, are still based on the older google guidelines while nowadays more modern approaches are available: (e.g. https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md)

(I could not see a tab in e.g. DataFormats/Headers/src/DataHeader.cxx - how do you look for it?)

**Comment by ihrivnac** [comment] 2017-12-15 17:20
I use a script for detecting tabulations, which I wrote some time ago for checking Geant4 examples, as we have the same rule here. The check was then added as an svn hook which does not allow the developers to commit such code. I can pass you the script offline.

**Comment by ktf** [comment] 2017-12-17 21:53
I think that the only guidelines we can realistically ask developers to follow are the ones enforced by a tool before merge time, possibly with automatic correction happening. Since we do have a test for those, it's just a matter of someone deciding that having a check for a given guideline has higher priority than something else they are doing. Having an issue open saying "coding guidelines are violated" will not get them fixed unless there is specific information provided.

If you would like to have the checks extended, feel free to open a PR for the code which does the check:

https://github.com/alisw/alidist/blob/master/o2checkcode.sh

or for the code checker itself:

https://github.com/AliceO2Group/O2CodeChecker.git

@mkrzewic I fixed all the tabs in #732.

**Comment by ihrivnac** [comment] 2017-12-18 10:43
I agree that the best way how to enforce following the guidelines is to have them checked automatically; from the script code it is however not clear which guidelines are checked and which are not. Is it somewhere documented which guidelines are checked? 
I am not the developer of the checking tools, so I don't plan to prepare a PR for its updates, but I hoped that the developers of the tool could add the checks, which are feasible, like those for  tabulations or data members.

**Comment by Barthelemy** [comment] 2017-12-18 12:19
@sawenzel might have something to say as he developed tools to check certain guidelines.

**Comment by ktf** [comment] 2017-12-19 01:20
The list of tests being performed is:

https://github.com/alisw/alidist/blob/master/o2checkcode.sh#L46

At the moment, apart from the standard "code moderniser" checks, the only AliceO2 specific test is the one for member variables starting with m rather than f, which I wrote a year ago or so and did all the cleanups for. There is additional tests from @sawenzel and @ZdravkoD and I think they plan to roll them in production at some point. There is also a few `google-*` options we could enable but the problem is always the usual: unless someone takes ownership of cleaning the errors upfront, rather than simply complaining about checks not being enforced, we will not converge.

**Comment by sawenzel** [comment] 2017-12-19 01:22
I think we need to distinguish slightly between pure formatting issues such as tabs and spacings and more C++ oriented static analysis. The former is in principle handled by `clang-format` and the latter to some extend by `O2CodeChecker`. 

We can easily enable clang-format to enfore/enable checks on spaces/tabs.

**Comment by ktf** [comment] 2017-12-19 01:55
Agreed. However enabling `clang-format` would need us to agree that our formatting guidelines are really whatever `clang-format` enforces and we adapt the style guide to them. This was always rejected / not carried through IIRC. @dberzano can we start the discussion again?
