### ISSUE TITLE
Error while running FLP2EPN on Mac (Sierra)

### ISSUE THREAD

**Issue by ktf** [AliceO2Group/AliceO2#229] opened 2017-02-07 14:30 UTC
Running:

`/Users/ktf/work/active/sw/BUILD/O2-latest/O2/bin/flpSyncSampler --id flpSyncSampler  --mq-config /Users/ktf/work/active/sw/BUILD/O2-latest/O2/bin/config/flp2epn-prototype.json --log-color 0 --event-rate 100 --network-interface en0`

results in:

```
...
[15:24:27][DEBUG] Using ZeroMQ library, version: 4.2.1
[15:24:27][STATE] Entering INITIALIZING DEVICE state
[15:24:27][INFO] bind socket flpSyncSampler.device-commands.pub on inproc://commands
[15:24:27][DEBUG] Validating channel "stf1[0]"... VALID
[15:24:27][INFO] bind socket flpSyncSampler.stf1[0].pub on tcp://127.0.0.1:5550
Invalid argument (src/tcp.cpp:78)
#0  0x580000010bf85018 in ? (zmq::zmq_abort(char const*)+0x9)
#1  0x10bfac9e9 in /opt/boxen/homebrew/opt/zeromq/lib/libzmq.5.dylib (zmq::set_tcp_send_buffer(int, int)+0x7b)
#2  0x10bfb0b05 in /opt/boxen/homebrew/opt/zeromq/lib/libzmq.5.dylib (zmq::tcp_listener_t::set_address(char const*)+0x16f)
#3  0x10bfa145f in /opt/boxen/homebrew/opt/zeromq/lib/libzmq.5.dylib (zmq::socket_base_t::bind(char const*)+0x6b2)
#4  0x10c477382 in /Users/ktf/work/active/sw/osx_x86-64/FairRoot/dev-13/lib/libFairMQ.16.dylib (FairMQSocketZMQ::Bind(std::__1::basic_string<char,
 std::__1::char_traits<char>, std::__1::allocator<char> > const&)+0x16c)
#5  0x10c4b5c4c in /Users/ktf/work/active/sw/osx_x86-64/FairRoot/dev-13/lib/libFairMQ.16.dylib (FairMQDevice::BindEndpoint(FairMQSocket&, std::__1
::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)+0x6f)
#6  0x10c4b31ff in /Users/ktf/work/active/sw/osx_x86-64/FairRoot/dev-13/lib/libFairMQ.16.dylib (FairMQDevice::AttachChannel(FairMQChannel&)+0x4e0)
#7  0x10c4b3f90 in /Users/ktf/work/active/sw/osx_x86-64/FairRoot/dev-13/lib/libFairMQ.16.dylib (FairMQDevice::BindChannels(std::__1::list<FairMQCh
annel*, std::__1::allocator<FairMQChannel*> >&)+0x61)
#8  0x10c4b3dd1 in /Users/ktf/work/active/sw/osx_x86-64/FairRoot/dev-13/lib/libFairMQ.16.dylib (FairMQDevice::InitWrapper()+0xf66)
#9  0x10c49ada6 in /Users/ktf/work/active/sw/osx_x86-64/FairRoot/dev-13/lib/libFairMQ.16.dylib (FairMQFSM::FairMQFSM_::Worker()+0x36)
#10  0x10c499fb6 in /Users/ktf/work/active/sw/osx_x86-64/FairRoot/dev-13/lib/libFairMQ.16.dylib (void* std::__1::__thread_proxy<std::__1::tuple<vo
id (FairMQFSM::FairMQFSM_::*)(), boost::msm::back::state_machine<FairMQFSM::FairMQFSM_, boost::parameter::void_, boost::parameter::void_, boost::p
arameter::void_, boost::parameter::void_>*> >(void*)+0x71)
#11  0x7fffa2227a68 in /usr/lib/system/libsystem_pthread.dylib (_pthread_body+0xb4)
#12  0x7fffa222798d in /usr/lib/system/libsystem_pthread.dylib (_pthread_body+0x0)
```

**Comment by ktf** [comment] 2017-02-07 14:32
@rbx

**Comment by MohammadAlTurany** [comment] 2017-02-07 14:35
@ktf using zmq 4.1.3  it works for me!

**Comment by ktf** [comment] 2017-02-07 14:57
I just noticed I am running 4.2.1. Also checking if I accidentally did not recompile...

**Comment by rbx** [comment] 2017-02-07 15:06
I can confirm the issue with zeromq 4.2.1.
I'll investigate to find a fix.
For now, can you rollback to zeromq 4.1.3 (the one in fairsoft)?

**Comment by rbx** [comment] 2017-02-09 11:31
This is now fixed in the dev branch of FairRoot.

**Closed** 2017-03-01 08:06 UTC
