### ISSUE TITLE
Compilation error (OSX Sierra)

### ISSUE THREAD

**Issue by dr4kan** [AliceO2Group/AliceO2#343] opened 2017-04-24 16:51 UTC
Dear all,

I get the following error when compiling O2 (installation from scratch). It cannot find some
include files from FairRoot, which was correctly built in the installation process though.

Any ideas?

Thanks,
Davide.

DEBUG:O2:0: [ 14%] Linking CXX shared library ../../../lib/libTPCBase.dylib
DEBUG:O2:0: ld: library not found for -lFairRoot::FairMQ
DEBUG:O2:0: clang: error: linker command failed with exit code 1 (use -v to see invocation)
DEBUG:O2:0: make[2]: *** [lib/libTPCBase.dylib] Error 1
DEBUG:O2:0: make[1]: *** [Detectors/TPC/base/CMakeFiles/TPCBase.dir/all] Error 2
DEBUG:O2:0: Scanning dependencies of target CCDB
DEBUG:O2:0: [ 14%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/Backend.cxx.o
DEBUG:O2:0: [ 15%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/BackendRiak.cxx.o
DEBUG:O2:0: [ 15%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/BackendOCDB.cxx.o
DEBUG:O2:0: [ 15%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/ConditionId.cxx.o
DEBUG:O2:0: [ 15%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/Condition.cxx.o
DEBUG:O2:0: [ 16%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/ConditionMetaData.cxx.o
DEBUG:O2:0: [ 16%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/GridStorage.cxx.o
DEBUG:O2:0: [ 16%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/FileStorage.cxx.o
DEBUG:O2:0: [ 17%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/IdPath.cxx.o
DEBUG:O2:0: [ 17%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/IdRunRange.cxx.o
DEBUG:O2:0: [ 17%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/LocalStorage.cxx.o
DEBUG:O2:0: [ 17%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/Manager.cxx.o
DEBUG:O2:0: [ 18%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/ObjectHandler.cxx.o
DEBUG:O2:0: [ 18%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/Storage.cxx.o
DEBUG:O2:0: [ 18%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/XmlHandler.cxx.o
DEBUG:O2:0: [ 18%] Building CXX object CCDB/CMakeFiles/CCDB.dir/G__CCDBDict.cxx.o
DEBUG:O2:0: [ 19%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/ConditionsMQServer.cxx.o
DEBUG:O2:0: [ 19%] Building CXX object CCDB/CMakeFiles/CCDB.dir/src/ConditionsMQClient.cxx.o
DEBUG:O2:0: [ 19%] Building CXX object CCDB/CMakeFiles/CCDB.dir/request.pb.cc.o
DEBUG:O2:0: /Users/davidepagano/alice/sw/SOURCES/O2/dev/0/CCDB/src/ConditionsMQClient.cxx:22:10: fatal error: 'options/FairMQProgOptions.h' file not found
DEBUG:O2:0: #include <options/FairMQProgOptions.h>
DEBUG:O2:0:          ^
DEBUG:O2:0: 1 error generated.
DEBUG:O2:0: make[2]: *** [CCDB/CMakeFiles/CCDB.dir/src/ConditionsMQClient.cxx.o] Error 1
DEBUG:O2:0: make[2]: *** Waiting for unfinished jobs....
DEBUG:O2:0: make[1]: *** [CCDB/CMakeFiles/CCDB.dir/all] Error 2
DEBUG:O2:0: make: *** [all] Error 2

**Comment by dennisklein** [comment] 2017-04-24 17:55
It looks like a mismatch of the FairRoot version and the AliceO2 version. Can you tell how exactly you build AliceO2 (which aliBuild commands)?

Your log output shows that you try to compile a recent AliceO2 version from the dev branch which depends on imported FairRoot targets, which was only added to FairRoot dev branch couple of weeks ago. A recent enough FairRoot version should fix both the linker error and the missing header.

**Comment by dr4kan** [comment] 2017-04-24 18:10
I started an installation from scratch (on a new Mac) and I  used `aliBuild --defaults o2 build O2` to build everything so it should take care of downloading the "right" version of all dependencies. Am I missing something?

**Comment by dennisklein** [comment] 2017-04-24 18:37
The `--defaults o2` seems currently out of sync.

To verify: Can you please go to your `alidist` folder and edit the file `fairroot.sh`. Replace `5ed20b7` with `4b0272a` in the two lines starting with `version:` and `tag:` and run `aliBuild --defaults o2 build O2`. If this throws the same errors, replace with `dev` and try again.

If any of the above works, pls open an issue in the https://github.com/alisw/alidist/issues repo, so that the maintainers can update the FairRoot dependency.

**Comment by dr4kan** [comment] 2017-04-24 19:31
With version `4b0272a` it's now failing at building FairRoot itself (see attachment). It seems to be related to ZeroMQ, which was compiled when building version `5ed20b7`. How to force to recompile it? I tried `aliBuild clean ZeroMQ` but it did nothing apparently.

[log.txt](https://github.com/AliceO2Group/AliceO2/files/952875/log.txt)

**Comment by dennisklein** [comment] 2017-04-24 20:17
The ZeroMQ installation looks fine. But we need to make sure, that FairRoot is built from scratch.

What is odd in your attached log file, is, that `libFairMQDDSConfigPlugin.dylib` tries to link against ZeroMQ, which it should not do at all. Other targets like `libFairMQ.dylib` should link against ZeroMQ and do so successfully judging from your logs.

I am currently trying to recreate your environment. But it will take a while.

**Comment by dr4kan** [comment] 2017-04-24 20:19
Thank you very much for your help. I wait for your news then.

**Comment by dennisklein** [comment] 2017-04-25 04:03
I could not reproduce your errors so far. Would you be willing to provide more debugging infos?

In your `/Users/davidepagano/alice` directory, could you 
1. run `alienv q`, `alienv list` and `aliBuild version` (from the same shell where you run the aliBuild build commands) and post the output here, then
2. edit the file `alidist/fairroot.sh` again and add the following lines just above the huge cmake statement in the middle of the file:
```
cmake --version
env
```
3. Replace the line `make ${JOBS:+-j 2} install` with `make VERBOSE=1 ${JOBS:+-j 2} install`.
4. Then run `aliBuild --defaults o2 build O2` (in the same shell as in 1.) and once it finished/failed attach the build log file of FairRoot (`/Users/davidepagano/alice/sw/BUILD/FairRoot-latest/log`) here.

Please review the output of the `env` command and make sure you won't post any sensitive/personal data here.

**Comment by dr4kan** [comment] 2017-04-25 06:07
Please find below the output of the commands you asked for. Thanks.

[output_alienv.txt](https://github.com/AliceO2Group/AliceO2/files/954029/output_alienv.txt)

```
$ alienv list
No Modulefiles Currently Loaded.
```

```
$ aliBuild version
aliBuild version: 1.4.0rc1
```

[fairroot_log.txt](https://github.com/AliceO2Group/AliceO2/files/954030/fairroot_log.txt)

**Comment by dennisklein** [comment] 2017-04-25 11:18
Can you run `csrutil status` and show the output?

**Comment by dr4kan** [comment] 2017-04-25 11:21
```
$ csrutil status
System Integrity Protection status: disabled.
```

**Comment by dennisklein** [comment] 2017-04-25 12:28
So to sum up my findings so far:

Your original error I commented earlier. The dev branch of the FairRoot repo was force pushed with a rewritten history which changed all the commit hash ids. For that reason I suggested pointing to the new hash id. In fact, on a fresh repo clone I cannot even checkout the old hash id any more. Probably you did it at a time when the github repo was not yet garbage collected or you had an older clone already, otherwise I cannot explain how you could have built FairRoot originally.

With the updated hash id, your system cannot find the libzmq lib file, because it searches the wrong  path - the `sw/INSTALLROOT/*` path is only temporarily used by aliBuild before the installed files get moved to `sw/osx_x86-64/*`. The INSTALLROOT path gets baked into the library file (`otool -L libzmq.dylib` will show you its "install_name"). But even if there is an absolute install_name the macos dynamic loader will honor DYLD_LIBRARY_PATH, we have tested it. You build log shows that linking libFairMQ succeeds:

```
[ 19%] Linking CXX shared library ../lib/libFairMQ.dylib
cd /Users/xxx/alice/sw/BUILD/37e06d6f145381ef36bbc9d68983f4cfab7f6512/FairRoot/fairmq && \
/usr/local/Cellar/cmake/3.8.0/bin/cmake -E cmake_link_script CMakeFiles/FairMQ.dir/link.txt \
--verbose=1
/Library/Developer/CommandLineTools/usr/bin/c++ -std=c++11 -O2 -g -Wshadow  -dynamiclib \
-Wl,-headerpad_max_install_names -single_module -undefined dynamic_lookup -flat_namespace  \
-o ../lib/libFairMQ.dylib -install_name @rpath/libFairMQ.dylib \
CMakeFiles/FairMQ.dir/FairMQChannel.cxx.o CMakeFiles/FairMQ.dir/FairMQConfigurable.cxx.o CMakeFiles/FairMQ.dir/FairMQDevice.cxx.o CMakeFiles/FairMQ.dir/FairMQLogger.cxx.o CMakeFiles/FairMQ.dir/FairMQMessage.cxx.o CMakeFiles/FairMQ.dir/FairMQPoller.cxx.o CMakeFiles/FairMQ.dir/FairMQSocket.cxx.o CMakeFiles/FairMQ.dir/FairMQStateMachine.cxx.o CMakeFiles/FairMQ.dir/FairMQTransportFactory.cxx.o CMakeFiles/FairMQ.dir/devices/FairMQBenchmarkSampler.cxx.o CMakeFiles/FairMQ.dir/devices/FairMQMerger.cxx.o CMakeFiles/FairMQ.dir/devices/FairMQMultiplier.cxx.o CMakeFiles/FairMQ.dir/devices/FairMQProxy.cxx.o CMakeFiles/FairMQ.dir/devices/FairMQSink.cxx.o CMakeFiles/FairMQ.dir/devices/FairMQSplitter.cxx.o CMakeFiles/FairMQ.dir/logger/logger.cxx.o CMakeFiles/FairMQ.dir/options/FairMQParser.cxx.o CMakeFiles/FairMQ.dir/options/FairMQProgOptions.cxx.o CMakeFiles/FairMQ.dir/options/FairMQSuboptParser.cxx.o CMakeFiles/FairMQ.dir/options/FairProgOptions.cxx.o CMakeFiles/FairMQ.dir/shmem/FairMQContextSHM.cxx.o CMakeFiles/FairMQ.dir/shmem/FairMQMessageSHM.cxx.o CMakeFiles/FairMQ.dir/shmem/FairMQPollerSHM.cxx.o CMakeFiles/FairMQ.dir/shmem/FairMQSocketSHM.cxx.o CMakeFiles/FairMQ.dir/shmem/FairMQTransportFactorySHM.cxx.o CMakeFiles/FairMQ.dir/zeromq/FairMQContextZMQ.cxx.o CMakeFiles/FairMQ.dir/zeromq/FairMQMessageZMQ.cxx.o CMakeFiles/FairMQ.dir/zeromq/FairMQPollerZMQ.cxx.o CMakeFiles/FairMQ.dir/zeromq/FairMQSocketZMQ.cxx.o CMakeFiles/FairMQ.dir/zeromq/FairMQTransportFactoryZMQ.cxx.o \
-lpthread \
/usr/local/opt/boost/lib/libboost_log-mt.dylib \
/usr/local/opt/boost/lib/libboost_log_setup-mt.dylib \
/usr/local/opt/boost/lib/libboost_program_options-mt.dylib \
/usr/local/opt/boost/lib/libboost_thread-mt.dylib \
/usr/local/opt/boost/lib/libboost_system-mt.dylib \
/usr/local/opt/boost/lib/libboost_filesystem-mt.dylib \
/usr/local/opt/boost/lib/libboost_regex-mt.dylib \
/usr/local/opt/boost/lib/libboost_date_time-mt.dylib \
/Users/xxx/alice/sw/osx_x86-64/ZeroMQ/v4.1.5-1/lib/libzmq.dylib \
/usr/local/opt/boost/lib/libboost_chrono-mt.dylib \
/usr/local/opt/boost/lib/libboost_system-mt.dylib \
/usr/local/opt/boost/lib/libboost_atomic-mt.dylib 
[ 19%] Built target FairMQ
```

But linking libFairMQDDSConfigPlugin fails, when resolving libzmq dependency, which is only a nested dependency even as you can see:
```
[ 21%] Linking CXX shared library ../../../lib/libFairMQDDSConfigPlugin.dylib
cd /Users/xxx/alice/sw/BUILD/37e06d6f145381ef36bbc9d68983f4cfab7f6512/FairRoot/fairmq/plugins/config && \
/usr/local/Cellar/cmake/3.8.0/bin/cmake -E cmake_link_script CMakeFiles/FairMQDDSConfigPlugin.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/c++ -std=c++11 -O2 -g -Wshadow  -dynamiclib \
-Wl,-headerpad_max_install_names -single_module -undefined dynamic_lookup -flat_namespace \
-compatibility_version 17.0.0 -current_version 17.3.0 -o ../../../lib/libFairMQDDSConfigPlugin.17.03.00.dylib \
-install_name @rpath/libFairMQDDSConfigPlugin.17.dylib \
CMakeFiles/FairMQDDSConfigPlugin.dir/FairMQDDSConfigPlugin.cxx.o \
 -L/usr/local/opt/boost/lib \
-Wl,-rpath,/usr/local/opt/boost/lib \
-Wl,-rpath,/Users/xxx/alice/sw/BUILD/37e06d6f145381ef36bbc9d68983f4cfab7f6512/FairRoot/lib -Wl,-rpath,/Users/xxx/alice/sw/osx_x86-64/DDS/master-1.4-1/lib \
../../../lib/libFairMQ.dylib \
-lpthread \
/Users/xxx/alice/sw/osx_x86-64/DDS/master-1.4-1/lib/libdds_intercom_lib.dylib \
/Users/xxx/alice/sw/osx_x86-64/DDS/master-1.4-1/lib/libdds_protocol_lib.dylib \
/Users/xxx/alice/sw/osx_x86-64/DDS/master-1.4-1/lib/libdds-user-defaults.dylib \
-ldl \
-lpthread \
/usr/local/opt/boost/lib/libboost_log-mt.dylib \
/usr/local/opt/boost/lib/libboost_log_setup-mt.dylib \
/usr/local/opt/boost/lib/libboost_program_options-mt.dylib \
/usr/local/opt/boost/lib/libboost_thread-mt.dylib \
/usr/local/opt/boost/lib/libboost_chrono-mt.dylib \
/usr/local/opt/boost/lib/libboost_atomic-mt.dylib \
/usr/local/opt/boost/lib/libboost_filesystem-mt.dylib \
/usr/local/opt/boost/lib/libboost_system-mt.dylib \
/usr/local/opt/boost/lib/libboost_regex-mt.dylib \
/usr/local/opt/boost/lib/libboost_date_time-mt.dylib 
ld: file not found: /Users/xxx/alice/sw/INSTALLROOT/c558a6c877a15af31da3823e5741920b2879d683/osx_x86-64/ZeroMQ/v4.1.5-1/lib/libzmq.5.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libFairMQDDSConfigPlugin.17.03.00.dylib] Error 1
```

So, at that stage the linker can only know about needing libzmq through libFairMQ. Let's try to find out which reference libFairMQ has learned when it was linked:

Can you pls find `libFairMQ.dylib` in `sw/BUILD/*` possibly and run `otool -L libFairMQ.dylib` and post the output?

**Comment by dr4kan** [comment] 2017-04-25 13:52
thanks again for your time. here's the output:

```
$ otool -L libFairMQ.dylib
libFairMQ.dylib:
	@rpath/libFairMQ.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.51.1)
	/usr/local/opt/boost/lib/libboost_log-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_log_setup-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_regex-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_date_time-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/davidepagano/alice/sw/INSTALLROOT/c558a6c877a15af31da3823e5741920b2879d683/osx_x86-64/ZeroMQ/v4.1.5-1/lib/libzmq.5.dylib (compatibility version 6.0.0, current version 6.1.0)
	/usr/local/opt/boost/lib/libboost_chrono-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_atomic-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
```

**Comment by dennisklein** [comment] 2017-04-25 14:08
Thx, I believe that narrows down the problem to the aliBuild ZeroMQ installation not being location independent on macos. Tomorrow I may have access to a mac in order to figure out how to make the aliBuild ZeroMQ installation location independent. Maybe there is also a way to fix it through the environment. I believe we already had these kind of issues in the past, I will ask some people.

**Comment by dr4kan** [comment] 2017-04-25 14:20
Ok thank you. I wait for your news.

**Comment by dennisklein** [comment] 2017-04-26 15:22
quick update: I have now access to a mac and could reproduce your libzmq linker error. Working on it now.

**Comment by dr4kan** [comment] 2017-04-26 15:25
Good, many thanks.

**Comment by dennisklein** [comment] 2017-04-26 16:41
I could manually relocate the `libzmq.5.dylib` file which fixed the error as I expected. While looking into the alibuild relocation code, I noticed that there is already a pending PR alisw/alibuild#420 which addresses the relocation issue. I will test it tomorrow and vote to move the PR forward.

**Comment by dr4kan** [comment] 2017-04-28 09:57
is anything changed about this? I ask because I started from scratch on another Mac, this time with El Capitan, and the installation fails for another problem (always when compiling FairRoot though). 

[log.txt](https://github.com/AliceO2Group/AliceO2/files/964000/log.txt)

**Comment by dennisklein** [comment] 2017-04-28 13:22
Hi, your last error is a mismatch between Boost and CMake versions. For Boost 1.64 one needs CMake 3.8.0+. This is because the `FindBoost.cmake` module currently used is shipped with CMake and it contains dependency information for the imported Boost targets which needs to be updated for each new Boost release.

**Comment by dr4kan** [comment] 2017-04-28 15:28
@dennisklein many thanks. that fixed the issue and I finally managed to compile o2 on El Capitain. Hopefully I will be able to compile it on Sierra too...

**Comment by dennisklein** [comment] 2017-05-05 12:25
@dr4kan update: I made a couple of PRs with `alidist`, `aliBuild` and `FairRoot`. It will take some time to get them merged, but you could get the patches now locally, if you wanted to move on faster. Unfortunately, it is not a trivial fix.

**Comment by dennisklein** [comment] 2017-05-17 21:18
@dr4kan update: the required change in `FairRoot` is merged. The required fix in aliBuild will be included in their next release. The alidist patch is still pending, but I have hopes we will get there when aliBuild gets released.

**Comment by dennisklein** [comment] 2017-05-24 12:54
@dr4kan update: The `alidist` patch just got included. You should expect the issues to be resolved in the next release of `aliBuild`, I guess `1.5.0`.

**Comment by sawenzel** [comment] 2017-08-02 06:34
Can we close this issue?

**Comment by sawenzel** [comment] 2017-08-21 16:21
Closing this. Please reopen if this is still an issue.

**Closed by sawenzel** 2017-08-21 16:21 UTC
