### ISSUE TITLE
O2 build stops during ROOT configuration

### ISSUE THREAD

**Issue by jniedzie** [AliceO2Group/AliceO2#831] opened 2018-02-05 14:07 UTC
I try to build O2 on macOS 10.13.3 with the following command:

`aliBuild -j8 --debug --defaults o2-daq build O2`

It breaks when configuring ROOT:

```
DEBUG:O2:ROOT:0: + FEATURES='builtin_pcre mathmore xml ssl opengl minuit2 http
DEBUG:O2:ROOT:0:             pythia6 roofit soversion vdt  cxx14
DEBUG:O2:ROOT:0:             alien monalisa builtin_freetype'
DEBUG:O2:ROOT:0: + bin/root-config --features
DEBUG:O2:ROOT:0: alien asimage astiff builtin_afterimage builtin_freetype builtin_ftgl builtin_gl2ps builtin_glew builtin_llvm builtin_lz4 builtin_pcre builtin_tbb builtin_unuran builtin_vdt cling cocoa cxx14 exceptions explicitlink gdml genvector http imt libcxx mathmore minuit2 mysql opengl pch pythia6 pythia6_nolink python roofit shared soversion sqlite ssl thread tmva vdt xml xrootd
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-builtin_pcre
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-mathmore
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-xml
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-ssl
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-opengl
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-minuit2
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-http
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-pythia6
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-roofit
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-soversion
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-vdt
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-cxx14
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-alien
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0: + for FEATURE in '$FEATURES'
DEBUG:O2:ROOT:0: + bin/root-config --has-monalisa
DEBUG:O2:ROOT:0: + grep -q yes
DEBUG:O2:ROOT:0:
ERROR:O2:ROOT:0: Error while executing /Users/Jeremi/alice-o2/sw/SPECS/osx_x86-64/ROOT/v6-12-04-2/build.sh on `jniedzie-macbook.dyndns.cern.ch'.
ERROR:O2:ROOT:0: Log can be found in /Users/Jeremi/alice-o2/sw/BUILD/ROOT-latest/log.
ERROR:O2:ROOT:0: Please upload it to CERNBox/Dropbox if you intend to request support.
ERROR:O2:ROOT:0: Build directory is /Users/Jeremi/alice-o2/sw/BUILD/ROOT-latest/ROOT.
```

The log file is here:[link](https://www.dropbox.com/s/aplsohavlf3gkim/log?dl=0)

**Comment by ktf** [comment] 2018-02-06 20:27
Mmm... Looks like we require monalisa also for the o2-daq case. @dberzano is that expected?

**Comment by dberzano** [comment] 2018-02-16 10:41
We do, because `ApMon` (the MonALISA client library) is part of the Monitoring package now. The ROOT recipe should be fixed to check for `APMON_VERSION` instead of AliEn-Runtime. I am taking care of that.

**Comment by dberzano** [comment] 2018-02-16 11:00
That said, @jniedzie, your problem cannot be reproduced on Mac. We only enable `-Dmonalisa=ON` if AliEn is there, and AliEn is _not_ there with `--defaults o2-daq`. My suspects are:

* outdated alidist
* ROOT in development mode and build directory therefore shared between ROOT builds with different defaults
* running `aliBuild` from within an `alienv` session

Try to erase completely your ROOT build directory:

```
rm -rf /Users/Jeremi/alice-o2/sw/BUILD/ROOT-latest/ROOT
```

Enabling MonALISA if the Monitoring package is on has to be done from us, but it is independent from the issue you're experiencing.

**Comment by matthiasrichter** [comment] 2018-03-26 11:47
Hi @jniedzie , is this issue solved or still valid?

**Comment by ktf** [comment] 2018-04-04 19:43
Closing this due to inactivity. Of course feel free to reopen if still broken.

**Closed by ktf** 2018-04-04 19:43 UTC
